# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/payment.proto\x12\x05proto\"2\n\x0ePaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1e\n\x0fPaymentResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x32[\n\x13PaymentNotification\x12\x44\n\x13NotifyPaymentStatus\x12\x15.proto.PaymentRequest\x1a\x16.proto.PaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTREQUEST']._serialized_start=30
  _globals['_PAYMENTREQUEST']._serialized_end=80
  _globals['_PAYMENTRESPONSE']._serialized_start=82
  _globals['_PAYMENTRESPONSE']._serialized_end=112
  _globals['_PAYMENTNOTIFICATION']._serialized_start=114
  _globals['_PAYMENTNOTIFICATION']._serialized_end=205
# @@protoc_insertion_point(module_scope)
