# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pagamento.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpagamento.proto\x12\tpagamento\"Z\n\x12NotificacaoRequest\x12\x11\n\tid_pedido\x18\x01 \x01(\x05\x12\x12\n\nid_cliente\x18\x02 \x01(\x05\x12\r\n\x05valor\x18\x03 \x01(\x02\x12\x0e\n\x06status\x18\x04 \x01(\t\"\'\n\x13NotificacaoResposta\x12\x10\n\x08mensagem\x18\x01 \x01(\t2i\n\x12NotificacaoService\x12S\n\x12NotificarPagamento\x12\x1d.pagamento.NotificacaoRequest\x1a\x1e.pagamento.NotificacaoRespostab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pagamento_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTIFICACAOREQUEST._serialized_start=30
  _NOTIFICACAOREQUEST._serialized_end=120
  _NOTIFICACAORESPOSTA._serialized_start=122
  _NOTIFICACAORESPOSTA._serialized_end=161
  _NOTIFICACAOSERVICE._serialized_start=163
  _NOTIFICACAOSERVICE._serialized_end=268
# @@protoc_insertion_point(module_scope)
