services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: livraria_ufc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123#@!
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: